### ISSUE TITLE
registrering two grandient with name 'scaleInvariantGradient'

### ISSUE THREAD

**Issue by MrMinemeet** [lmb-freiburg/deeptam#12]
Hi,

I'm trying to get DeepTAM running but at the moment I'm stuck with the following error message

> KeyError: "Registering two gradient with name 'ScaleInvariantGradient' !(Previous registration was in __init__ /home/adas/DeepTAM/deeptam/tracking/python/deeptam_tracker/tracker.py:231)"

Every other problem was more or less easy to find out but this is very hard and I can't get it worked out.

Here would be the full stack trace if it helps:
https://pastebin.com/2qu72vnJ
```
Using /home/adas/DeepTAM/lmbspecialops/build/lib/lmbspecialops.so
Traceback (most recent call last):
  File "example_basic.py", line 102, in <module>
    main()
  File "example_basic.py", line 72, in main
    tracker_core = TrackerCore(tracking_module_path,checkpoint,intrinsics)
  File "/home/adas/DeepTAM/deeptam/tracking/python/deeptam_tracker/tracker.py", line 231, in __init__
    self._tracking_mod = load_myNetworks_module_noname(self._tracking_module)
  File "/home/adas/DeepTAM/deeptam/tracking/python/deeptam_tracker/utils/helpers.py", line 44, in load_myNetworks_module_noname
    return load_myNetworks_module(module_name, path_to_myNetworks)
  File "/home/adas/DeepTAM/deeptam/tracking/python/deeptam_tracker/utils/helpers.py", line 32, in load_myNetworks_module
    return importlib.import_module('.'+myNetworks_name, module_name)
  File "/home/adas/.virtualenvs/DeepTAM/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../python/deeptam_tracker/models/networks.py", line 6, in <module>
    from .blocks import *
  File "../python/deeptam_tracker/models/blocks.py", line 1, in <module>
    from .helpers import *
  File "../python/deeptam_tracker/models/helpers.py", line 4, in <module>
    spec.loader.exec_module(foo)
  File "/home/adas/DeepTAM/lmbspecialops/python/lmbspecialops.py", line 356, in <module>
    @ops.RegisterGradient("ScaleInvariantGradient")
  File "/home/adas/.virtualenvs/DeepTAM/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2085, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/home/adas/.virtualenvs/DeepTAM/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'ScaleInvariantGradient' !(Previous registration was in __init__ /home/adas/DeepTAM/deeptam/tracking/python/deeptam_tracker/tracker.py:231)"
Tensorflow graph reseted
```

This happens when running the example_basic.py or example_advanced_sequence.py

Hope you have an idea how to fix it

**Comment by MrMinemeet** [comment]
I don't get the error anymore but didn't actively do anything to fix it.  So it's kinda fixed but still if someone would know how to fix it please write it here so that others can see it.
